### PR TITLE
Add TryFrom &str and String impl for Regex

### PR DESCRIPTION
**Pull request by ch3pjw**
This brings it to parity with the underlying [`regex`](https://docs.rs/regex/latest/src/regex/regex/string.rs.html#129-136) library

### CODE REVIEW

**Review by keith-hall — APPROVED** [review]

**Comment by robinst** [comment]
Hi! Changes LGTM, but there's conflicts now. Can you resolve them so we can merge?

**Comment by robinst** [comment]
> Can you resolve them so we can merge?

I've done that now using the online editor (didn't know GitHub had that).

**Comment by robinst** [comment]
Released this and the other change in version 0.12.0: https://github.com/fancy-regex/fancy-regex/blob/main/CHANGELOG.md

**Comment by ch3pjw** [comment]
Great, thanks @robinst!

**Pull request merged**
